# Example Docker Compose setup with Ollama
# This demonstrates how to run gollama-chat with a local Ollama instance

services:
  # Ollama service for LLM inference
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    # Uncomment for GPU support (requires nvidia-docker)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # gollama-chat TUI accessible via web browser
  gollama-chat:
    image: ghcr.io/kevensen/gollama-chat:latest
    ports:
      - "8080:8080"
    volumes:
      - gollama-config:/home/appuser/.local/share/gollama-chat/settings
    environment:
      TERM: xterm-256color
    restart: unless-stopped
    depends_on:
      - ollama
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Optional: ChromaDB for RAG functionality
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      CHROMA_SERVER_HOST: 0.0.0.0
      CHROMA_SERVER_HTTP_PORT: 8000
    restart: unless-stopped

volumes:
  gollama-config:
    driver: local
  ollama-data:
    driver: local
  chroma-data:
    driver: local
